config/routes.rb
Rails.application.routes.draw do
  get 'orders', to: 'orders#orders'
  devise_for :users
  devise_scope :user do  
    get 'address', to: 'users/registrations#address'
  end
  get 'profile', to: 'users#profile'
  get 'categories', to: 'categories#index'
  get 'product', to: 'products#new'
  post 'product', to: 'products#create'
  get 'products/:id', to: 'products#show', as: 'show_product'
  get 'add_category', to: 'categories#new'
  get 'cart', to: 'products#cart'
  get 'cart/:id', to: 'products#destroy', as: 'destroy'
  root 'products#index'
end

app/models/product.rb
class Product < ApplicationRecord
  has_and_belongs_to_many :categories
  has_one_attached :product_image
  belongs_to :user
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def show
    @product = Product.all.find(params[:id])
  end
  
  def cart  
    @shopping_cart = []
    @product = Product.all.find(params[:id])
  end

  def edit
  end

  def create
    @product = current_user.products.create(product_params)
    @product.product_image.attach(product_params[:product_image])
    @product.categories << Category.find(params[:category])
    if @product.save 
      redirect_to root_path
    else 
      flash[:alert] = product.errors.full_messages.join('<br>')
    end 
  end

  def destroy
    Product.all.find(params[:id]).destroy
    redirect_to root_path 
    flash[:alert] = "You have successfully purchased your item"
  end

  private 
  def product_params 
    params.permit(:name, :price, :description, :product_image)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/cart.html.erb
<h1 class="title text">Shopping Cart</h1>
<% @shopping_cart << @product %>
<% if @shopping_cart.length == 0  %>
  <p>Your Shopping Cart is empty</p>
  <% else %>
    <% @shopping_cart.each do |product| %>
      <div class="displayitem column">
      <header class="card-header">
        <p class="card-header-title text has-text-centered">
          <%= product.name %>
        </p>
      </header>
      <figure class="image">
        <div style="max-width:400px; max-height:400px;">
        <% if product.product_image.attached? %>
          <%= image_tag(product.product_image, style:"width:100%; height: 100%;")  %>
        <% else %>
          <img src="http://lorempixel.com/200/200" alt="Placeholder image">
        <% end%>
        </div>
      </figure>
      <div class="card-content">
        <div class="content">
          <%= product.description %>
        </div>
      </div>
      <footer class="card-footer">
        <li class="card-footer-item"><%= product.price %></li>
        <li class="card-footer-item"> <%= product.rating %></li>
        <li class="card-footer-item"><%=  product.categories[0].name %></li>
      </footer>
    </div>
  <% end %>
  <button class="button is-success"><%= link_to("Buy Now", destroy_path(id: @product.id)) %></button>
<% end %>

app/views/products/index.html.erb
<% provide(:title, "Home")%>
<% provide(:background, image_tag("shopping_cart.png", class: "background-image")) %>
<%= render 'layouts/searchbar' %>
 <div class="card-pos card columns is-variable">
<% @products.sample(9).each do |product| %>
<%= link_to show_product_path(product) do %>
  <div class="displayitem column">
    <header class="card-header">
      <p class="card-header-title text has-text-centered">
        <%= product.name %>
      </p>
    </header>
    <figure class="image">
      <div style="max-width:400px; max-height:400px;">
      <% if product.product_image.attached? %>
        <%= image_tag(product.product_image, style:"width:100%; height: 100%;")  %>
      <% else %>
        <img src="http://lorempixel.com/200/200" alt="Placeholder image">
      <% end%>
    </div>
    </figure>
    <div class="card-content">
      <div class="content">
        <%= product.description %>
      </div>
    </div>
    <footer class="card-footer">
      <li class="card-footer-item"><%= product.price %></li>
      <li class="card-footer-item"> <%= product.rating %></li>
      <li class="card-footer-item"><%=  product.categories[0].name %></li>
    </footer>
    </div>
    <% end %>
<% end %>
</div>

app/views/products/items.html.erb
<h1>Your Listed Items</h1>
<%= current_user.products.each do |product| %>
  <div class="displayitem column">
    <header class="card-header">
      <p class="card-header-title text has-text-centered">
        <%= product.name %>
      </p>
    </header>
    <figure class="image">
      <img src="http://lorempixel.com/200/200" alt="Placeholder image">
    </figure>
    <div class="card-content">
      <div class="content">
        <%= product.description %>
      </div>
    </div>
    <footer class="card-footer">
      <li class="card-footer-item"><%= product.price %></li>
      <li class="card-footer-item"> <%= product.rating %></li>
      <li class="card-footer-item"><%=  product.categories[0].name %></li>
    </footer>
    </div>
<% end %>

app/views/products/new.html.erb
<h1 class="title">Sell a Product</h1>
  <%= form_with model: @products, local: true do |f| %>
<div class="field">
  <label class="label"><%= f.label :product_image %>
  <%= f.file_field :product_image %>
</div>
<div class="field">
  <label class="label"<%= f.label :name %></label>
  <input class="input"<%= f.text_field :name %>
</div>
<div class="field">
  <label class="label"<%= f.label :price %></label>
  <input class="input"<%= f.number_field :price %>
</div>
<div class="field">
  <label class="label"<%= f.label :description %></label>
  <input class="input"<%= f.text_field :description %>
</div>

<p class="control">
  <span class="select">
    <%= f.select :category, options_for_select(Category.all.map{ |cat| [cat.name, cat.id]} ), {prompt:'select'}%>
  </span>
</p>
<br>
<div class="columns">
  <div class="column">
    <button class="button is-primary" type="submit">Sell Item</button>
    <%= link_to "Back", :back, class: "button is-link is-light" %>
  </div>
</div>
<% end %>

app/views/products/show.html.erb
<div class="modal is-active">
<div class="modal-background"></div>
<div class="modal-card">
  <header class="modal-card-head">
    <p class="modal-card-title"><% @product.name %></p>
    <button  class="delete" aria-label="close"></button>
  </header>
  <section class="modal-card-body">
    <h1 class="title has-text-centered"><%= @product.name %></h1>
      <div style="max-width:400px; max-height:400px;">
      <% if @product.product_image.attached? %>
        <%= image_tag(@product.product_image, style:"width:100%; height: 100%;")  %>
      <% else %>
        <img src="http://lorempixel.com/200/200" alt="Placeholder image">
      <% end%>
      </div>
    <br>
    <p class="text has-text-centered"><%= @product.description %></p>
    <footer class="card-footer">
    <li class="card-footer-item"><%= @product.price %></li>
    <li class="card-footer-item"> <%= @product.rating %></li>
    <li class="card-footer-item"><%=  @product.categories[0].name %></li>
  </section>
  <footer class="modal-card-foot">
  <% if user_signed_in? %>
    <button class="button is-success is-outlined"><%= link_to "Add to Cart", cart_path(id: @product.id) %></button>
  <% else %>
    <p>Please login to continue</p>
  <% end %>
    <button class="button is-info is-outlined"><%= link_to "Cancel", root_path %></button>
  </footer>
</div>
</div>
</button>